[package]
name = "bevy-hophy-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-hophy = {path="../bevy-hophy"}
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true
